/**
 * Modern gri tema (zinc / slate çizgisi):
 * — Açık: çok hafif gri zemin, beyaz kartlar, kömür primary; profesyonel ve sakin.
 * — Koyu: zinc ölçeği; katmanlı yüzey; tam gri semantik vurgular.
 */

/** Açık mod: premium nötr — beyaza yakın zemin, net kontrast */
export const lightPalette = {
  background: '#FAFAFA',
  surface: '#FFFFFF',
  surfaceSubtle: '#F4F4F5',
  primary: '#18181B',
  primaryLight: '#F1F5F9',
  onPrimary: '#FAFAFA',
  textPrimary: '#0F172A',
  textSecondary: '#64748B',
  textTertiary: '#94A3B8',
  success: '#15803D',
  warning: '#B45309',
  danger: '#B91C1C',
  border: '#E4E4E7',
  borderStrong: '#D4D4D8',
  calendarMuted: '#F1F5F9',
  calendarSelectedText: '#FAFAFA',
  overlayBackdrop: 'rgba(15, 23, 42, 0.48)',
  badgeDoneBg: '#ECFDF5',
  badgeDoneText: '#166534',
  badgePendingBg: '#FFFBEB',
  badgePendingText: '#B45309',
  shadowColor: '#0F172A',
  shadowOpacityCard: 0.055,
  shadowRadiusCard: 20,
  shadowOffsetYCard: 10,
  elevationCard: 5,
  shadowOpacitySm: 0.038,
  shadowRadiusSm: 12,
  shadowOffsetYSm: 6,
  elevationSm: 3,
  /** Ana sayfa header bandı ile aynı — yalnızca açık tema; görev/ayarlar CTA’ları */
  ctaMuted: '#3D3E44',
  onCtaMuted: '#FAFAFA',
};

/** Koyu mod: modern zinc gri — derinlik katmanları */
export const darkPalette = {
  background: '#09090B',
  surface: '#18181B',
  surfaceSubtle: '#27272A',
  primary: '#FAFAFA',
  primaryLight: '#27272A',
  onPrimary: '#18181B',
  textPrimary: '#FAFAFA',
  textSecondary: '#A1A1AA',
  textTertiary: '#71717A',
  success: '#A1A1AA',
  warning: '#D4D4D8',
  danger: '#F4F4F5',
  border: '#3F3F46',
  borderStrong: '#52525B',
  calendarMuted: '#27272A',
  calendarSelectedText: '#18181B',
  overlayBackdrop: 'rgba(9, 9, 11, 0.78)',
  badgeDoneBg: 'rgba(250, 250, 250, 0.1)',
  badgeDoneText: '#FAFAFA',
  badgePendingBg: 'rgba(161, 161, 170, 0.12)',
  badgePendingText: '#D4D4D8',
  shadowColor: '#000000',
  shadowOpacityCard: 0.45,
  shadowRadiusCard: 22,
  shadowOffsetYCard: 12,
  elevationCard: 8,
  shadowOpacitySm: 0.32,
  shadowRadiusSm: 12,
  shadowOffsetYSm: 6,
  elevationSm: 4,
};
